spring:
  # 配置文件名称，用来标识不同环境的配置。由 spring.profiles.active 的值来决定使用哪组配置。
  ## 简单尝试
#  profiles: path_route
  application:
    # 应用名称
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        # 路由标识（id：标识，具有唯一性）   简单尝试
        - id: user-gateway
          uri: lb://user-service
          predicates:
            - Path=/ms-user/**
          filters:
            - StripPrefix=1
        - id: order-gateway
          uri: lb://order-service
          predicates:
            - Path=/ms-order/**
          filters:
            - StripPrefix=1